# Change these first
owner: ajshovon # Your GitHub organization or username, where this repository lives
repo: status.shovon.me # The name of this repository

sites:
  - name: shovon.me
    url: https://shovon.me
  - name: shovon.xyz
    url: https://shovon.xyz
#  - name: KVM SG
#    check: "tcp-ping"
#    url: $KVM_SG
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.shovon.me
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: "Status :: [.shovon]"
  introTitle: "Status :: [.shovon]"
  introMessage: "Server status page of [.shovon]"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  themeUrl: https://status.shovon.me/dark.css
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
